# 4 Pre-Processing and Training Data<a id='4_Pre-Processing_and_Training_Data'></a>

In [1]:
# Importing the libraries
import pandas as pd
import numpy as np
from numpy import median
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from scipy import stats

## Load the data

In [2]:
# load the data
df = pd.read_csv('clean_data.csv')

In [3]:
df.head()

,CustomerID,Gender,Senior Citizen,Partner,Dependents,Tenure,Phone Service,Multiple Lines,Internet Service,Online Security,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,7590-VHVEG,0,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,1,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,1,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,1,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,0,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
# Remove 'CustomerID'

In [5]:
df2 = df.iloc[:,1:]

In [6]:
# df2 = df2.drop('Tenure', 1)

In [7]:
df2.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,0,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,1,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,1,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,1,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,0,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [8]:
#The next step is addressing our target variable, Churn. 
#Currently, the values of this feature are “Yes” and “No”. 
#This is a binary outcome, which is what we want, but our model will not be able to meaningfully interpret this in its current string-form. 
#Instead, we want to replace these variables with numeric binary values:

In [9]:
df2.Churn.replace({"Yes":1, "No":0}, inplace = True)

## Creat dummy features for object type features

In [10]:
dummy_df = pd.get_dummies(df2, drop_first=True)
# dummy_df = pd.get_dummies(df2)

In [11]:
dummy_df.shape

(6490, 31)

In [12]:
dummy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6490 entries, 0 to 6489
Data columns (total 31 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Gender                                  6490 non-null   int64
 1   Senior Citizen                          6490 non-null   int64
 2   Tenure                                  6490 non-null   int64
 3   Monthly Charges                         6490 non-null   float64
 4   Total Charges                           6490 non-null   float64
 5   Churn                                   6490 non-null   int64
 6   Partner_Yes                             6490 non-null   uint8
 7   Dependents_Yes                          6490 non-null   uint8
 8   Phone Service_Yes                       6490 non-null   uint8
 9   Multiple Lines_No phone service         6490 non-null   uint8
 10  Multiple Lines_Yes                      6490 non-null   uint8
 11  Internet Service_Fiber optic            6490 non-null   uint8
 12  Internet Service_No                     6490 non-null   uint8
 13  Online Security_No internet service     6490 non-null   uint8
 14  Online Security_Yes                     6490 non-null   uint8
 15  Online Backup_No internet service       6490 non-null   uint8
 16  Online Backup_Yes                       6490 non-null   uint8
 17  Device Protection_No internet service   6490 non-null   uint8
 18  Device Protection_Yes                   6490 non-null   uint8
 19  Tech Support_No internet service        6490 non-null   uint8
 20  Tech Support_Yes                        6490 non-null   uint8
 21  Streaming TV_No internet service        6490 non-null   uint8
 22  Streaming TV_Yes                        6490 non-null   uint8
 23  Streaming Movies_No internet service    6490 non-null   uint8
 24  Streaming Movies_Yes                    6490 non-null   uint8
 25  Contract_One year                       6490 non-null   uint8
 26  Contract_Two year                       6490 non-null   uint8
 27  Paperless Billing_Yes                   6490 non-null   uint8
 28  Payment Method_Credit card (automatic)  6490 non-null   uint8
 29  Payment Method_Electronic check         6490 non-null   uint8
 30  Payment Method_Mailed check             6490 non-null   uint8
dtypes: float64(2), int64(4), uint8(25)
memory usage: 462.8 KB

In [13]:
# drop outliners
from scipy import stats
dummy_df = dummy_df[(np.abs(stats.zscore(dummy_df)) < 3).all(axis=1)]

In [14]:
dummy_df.shape

(5877, 31)

In [15]:
dummy_df.to_csv (r'C:/Users/Nick/Documents/GitHub/Data-Science-Capstone-Three/Customer Churn/notebooks/dummy_df.csv', index = False, header=True)